/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem2 {
    public static void main(String[] args){
        int previous = 1;
        int current = 2;
        int temp;
        int sum = 2;    // starting terms are 1 & 2, so sum of even terms starts at 2

        for(int i = 3; current < 4000000; i++){
            temp = previous + current;
            previous = current;
            current = temp;

            if(temp % 2 == 0)
                sum += temp;
        }

        System.out.println("The sum of even-valued terms is " + sum);
    }
}
